server:
  port: 8080

spring:
  application:
    name: xsyq-backend
  profiles:
    active: dev
  
  # 鏁版嵁搴撻厤缃紙鏈湴锛?
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xsyq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: xsyq
    password: 2jLLw5Wf7F3A3TL7 # 鐢ㄦ埛闇€鏍规嵁鏈湴鐜淇敼

  # Redis閰嶇疆锛堟湰鍦帮級
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # password: password

# MyBatis-Plus 閰嶇疆
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 寮€鍙戞椂鎵撳嵃SQL

# JWT 閰嶇疆鑷畾涔?
jwt:
  secret: n2r5u8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWnZr4u7x!A%D*G-KaNdRg # 杩欎釜瀵嗛挜闇€瑕侀暱涓€鐐癸紝鐢熶骇鐜寤鸿鏀惧湪鐜鍙橀噺
  accessTokenExpiration: 7200000       # 2灏忔椂
  refreshTokenExpiration: 604800000    # 7澶?
  adminTokenExpiration: 86400000       # 绠＄悊鍛橀粯璁?4灏忔椂


aliyun:
  ai:
    api-key: sk-3b50dcc8bf3c4e3aa6f29ef70e902af8
    model: qwen-plus
